services:
  dreambox-integration:
    image: dreambox-integration
    build: ./
    container_name: dreambox-integration
    restart: unless-stopped
    network_mode: host  # Required for network discovery and magic packets
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - UC_CONFIG_HOME=/app/config
      - UC_DATA_HOME=/app/data